=== MaxwellDAnderson/sandbox/nac/reg-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- xmlns="https://www.w3schools.com" elementFormDefault="qualified" -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="nac">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="num">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="heading" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="chapeau" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="chapter">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="num">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="id" type="xs:string" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="heading" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="chapeau" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="section">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="num">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="id" type="xs:string" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1" />
                          <xs:element name="text">
                            <xs:complexType mixed="true">
                              <xs:sequence>
                                <xs:element name="xref" minOccurs="0" maxOccurs="unbounded" >
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="href" type="xs:string" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="subsection">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="num">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="id" type="xs:string" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1" />
                                <xs:element name="text">
                                  <xs:complexType mixed="true">
                                    <xs:sequence>
                                      <xs:element name="xref" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                              <xs:attribute name="href" type="xs:string" use="required" />
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="paragraph">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="num">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                              <xs:attribute name="id" type="xs:string" use="required" />
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1" />
                                      <xs:element name="text">
                                        <xs:complexType mixed="true">
                                          <xs:sequence>
                                            <xs:element name="xref" minOccurs="0" maxOccurs="unbounded">
                                              <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                    <xs:attribute name="href" type="xs:string" use="required" />
                                                  </xs:extension>
                                                </xs:simpleContent>
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="subparagraph">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="num">
                                              <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                    <xs:attribute name="id" type="xs:string" use="required" />
                                                  </xs:extension>
                                                </xs:simpleContent>
                                              </xs:complexType>
                                            </xs:element>
                                            <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1" />
                                            <xs:element name="text">
                                              <xs:complexType mixed="true">
                                                <xs:sequence>
                                                  <xs:element name="xref" minOccurs="0" maxOccurs="unbounded">
                                                    <xs:complexType>
                                                      <xs:simpleContent>
                                                        <xs:extension base="xs:string">
                                                          <xs:attribute name="href" type="xs:string" use="required" />
                                                        </xs:extension>
                                                      </xs:simpleContent>
                                                    </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                              </xs:complexType>
                                            </xs:element>
                                            <xs:element name="clause">
                                              <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="num">
                                                    <xs:complexType>
                                                      <xs:simpleContent>
                                                        <xs:extension base="xs:string">
                                                          <xs:attribute name="id" type="xs:string" use="required" />
                                                        </xs:extension>
                                                      </xs:simpleContent>
                                                    </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                  <xs:element name="text">
                                                    <xs:complexType mixed="true">
                                                      <xs:sequence>
                                                        <xs:element name="xref" minOccurs="0" maxOccurs="unbounded">
                                                          <xs:complexType>
                                                            <xs:simpleContent>
                                                              <xs:extension base="xs:string">
                                                                <xs:attribute name="href" type="xs:string" use="required" />
                                                              </xs:extension>
                                                            </xs:simpleContent>
                                                          </xs:complexType>
                                                        </xs:element>
                                                      </xs:sequence>
                                                    </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="subclause">
                                                    <xs:complexType>
                                                      <xs:sequence>
                                                        <xs:element name="num">
                                                          <xs:complexType>
                                                            <xs:simpleContent>
                                                              <xs:extension base="xs:string">
                                                                <xs:attribute name="id" type="xs:string" use="required" />
                                                              </xs:extension>
                                                            </xs:simpleContent>
                                                          </xs:complexType>
                                                        </xs:element>
                                                        <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                        <xs:element name="text">
                                                          <xs:complexType mixed="true">
                                                            <xs:sequence>
                                                              <xs:element name="xref" minOccurs="0" maxOccurs="unbounded">
                                                                <xs:complexType>
                                                                  <xs:simpleContent>
                                                                    <xs:extension base="xs:string">
                                                                      <xs:attribute name="href" type="xs:string" use="required" />
                                                                    </xs:extension>
                                                                  </xs:simpleContent>
                                                                </xs:complexType>
                                                              </xs:element>
                                                            </xs:sequence>
                                                          </xs:complexType>
                                                        </xs:element>
                                                        <xs:element name="item">
                                                          <xs:complexType>
                                                            <xs:sequence>
                                                              <xs:element name="num">
                                                                <xs:complexType>
                                                                  <xs:simpleContent>
                                                                    <xs:extension base="xs:string">
                                                                      <xs:attribute name="id" type="xs:string" use="required" />
                                                                    </xs:extension>
                                                                  </xs:simpleContent>
                                                                </xs:complexType>
                                                              </xs:element>
                                                              <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                              <xs:element name="text">
                                                                <xs:complexType mixed="true">
                                                                  <xs:sequence>
                                                                    <xs:element name="xref" minOccurs="0" maxOccurs="unbounded">
                                                                      <xs:complexType>
                                                                        <xs:simpleContent>
                                                                          <xs:extension base="xs:string">
                                                                            <xs:attribute name="href" type="xs:string" use="required" />
                                                                          </xs:extension>
                                                                        </xs:simpleContent>
                                                                      </xs:complexType>
                                                                    </xs:element>
                                                                  </xs:sequence>
                                                                </xs:complexType>
                                                              </xs:element>
                                                            </xs:sequence>
                                                          </xs:complexType>
                                                        </xs:element>
                                                      </xs:sequence>
                                                    </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MaxwellDAnderson/sandbox/nac/id-sample-output-1.xml
<?xml version="1.0" encoding="UTF-8" ?>

<nac xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="reg-1.xsd">
  <title>
    <num id="/nac/100">100</num>
    <heading>Generic Regulations</heading>
    <chapter>
      <num id="/nac/100/1">1</num>
      <heading>Generic Chapter</heading>
      <text>Lorem Ipsum</text>
      <section>
        <num id="/nac/100/1/1">1.1</num>
        <label>Generic Section Label</label>
        <text>Section Text</text>
        <subsection>
          <num id="/nac/100/1/1/a">1.1(a)</num>
          <label>Generic Subsection Label</label>
          <text>Subsection Text</text>
          <paragraph>
            <num id="/nac/100/1/1/a/1">1.1(a)(1)</num>
            <label>Generic Paragraph Label</label>
            <text>Paragraph Text</text>
            <subparagraph>
              <num id="/nac/100/1/1/a/1/i">1.1(a)(1)(i)</num>
              <label>Generic Paragraph Label</label>
              <text>Paragraph Text</text>
              <clause>
                <num id="/nac/100/1/1/a/1/i/A">1.1(a)(1)(i)(A)</num>
                <label>Generic Subparagraph Label</label>
                <text>Subparagraph Text</text>
                <subclause>
                  <num id="/nac/100/1/1/a/1/i/A/1">1.1(a)(1)(i)(A)(1)</num>
                  <label>Generic Subclause Label</label>
                  <text>Subclause Text</text>
                  <item>
                    <num id="/nac/100/1/1/a/1/i/A/1/i">1.1(a)(1)(i)(A)(1)(i)</num>
                    <label>Generic Item Label</label>
                    <text>Item Text</text>
                  </item>
                </subclause>
              </clause>
            </subparagraph>
          </paragraph>
        </subsection>
      </section>
    </chapter>
  </title>
</nac>
